#!/bin/sh 
# Run this in the test directory.
#
savetemps=n
rmtemps() {
  rm -f testpasserrs
  rm -f testpass
  rm -f testfails
}
rmtemps
stsecs=`date '+%s'`

echo "Start tsearch tests"
date 
x=`pwd` 
if [ ! -f RUNTEST ]
then
   echo "Run RUNTEST in the test directory, not in "
   pwd
   exit 1
fi
cd ../src
make
cd $x
pwd 
echo 
# use --std to run basic correctness tests.
#for opts in "--std" "testwords" "sortedwords"
for opts in "testwords" "sortedwords"
do
  for app  in  ../src/binarysearch ../src/eppingerdel ../src/balancedsearch ../src/redblack ../src/gnusearch ../src/hashsearch
#  for app  in  ../src/binarysearch
  do
    name=`basename  $app`
    echo "==== $app $opts ===="
    /usr/bin/time $app $opts  
  done
done
cd ..
sh scripts/CLEANUP
if [ $? -ne 0 ]
then
  echo "file cleanup failed!"
  exit 1
fi
exit 0
