langage: c
os: linux
dist: bionic
cache: true

compiler:
  - gcc
  - clang
os: linux

arch:
  - amd64
  - arm64

install:
  - sudo apt-get -qq update
  - sudo apt install build-essential

before_script:
  - autoreconf -vif

script: 
  - ./configure --enable-wall && make
